apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: homzy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dephomzy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15
