apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: homzy
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: homzy
  type: NodePort
status:
  loadBalancer: {}
